# Translations template for keystone.
# Copyright (C) 2014 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: keystone 2014.2.dev64.g1ac4379\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2014-08-04 06:05+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: keystone/clean.py:24
#, python-format
msgid "%s cannot be empty."
msgstr ""

#: keystone/clean.py:26
#, python-format
msgid "%(property_name)s cannot be less than %(min_length)s characters."
msgstr ""

#: keystone/clean.py:31
#, python-format
msgid "%(property_name)s should not be greater than %(max_length)s characters."
msgstr ""

#: keystone/clean.py:40
#, python-format
msgid "%(property_name)s is not a %(display_expected_type)s"
msgstr ""

#: keystone/cli.py:141
msgid "keystone-manage pki_setup is not recommended for production use."
msgstr ""

#: keystone/cli.py:160
msgid "keystone-manage ssl_setup is not recommended for production use."
msgstr ""

#: keystone/cli.py:218
msgid "At least one option must be provided"
msgstr ""

#: keystone/cli.py:225
msgid "--all option cannot be mixed with other options"
msgstr ""

#: keystone/cli.py:234
#, python-format
msgid "Unknown domain '%(name)s' specified by --domain-name"
msgstr ""

#: keystone/exception.py:49
msgid "missing exception kwargs (programmer error)"
msgstr ""

#: keystone/exception.py:79
#, python-format
msgid ""
"Expecting to find %(attribute)s in %(target)s - the server could not "
"comply with the request since it is either malformed or otherwise "
"incorrect. The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:90
#, python-format
msgid "%(detail)s"
msgstr ""

#: keystone/exception.py:94
msgid ""
"Timestamp not in expected format. The server could not comply with the "
"request since it is either malformed or otherwise incorrect. The client "
"is assumed to be in error."
msgstr ""

#: keystone/exception.py:103
#, python-format
msgid ""
"String length exceeded.The length of string '%(string)s' exceeded the "
"limit of column %(type)s(CHAR(%(length)d))."
msgstr ""

#: keystone/exception.py:109
#, python-format
msgid ""
"Request attribute %(attribute)s must be less than or equal to %(size)i. "
"The server could not comply with the request because the attribute size "
"is invalid (too large). The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:119
#, python-format
msgid ""
"The password length must be less than or equal to %(size)i. The server "
"could not comply with the request because the password is invalid."
msgstr ""

#: keystone/exception.py:127
msgid ""
"The certificates you requested are not available. It is likely that this "
"server does not use PKI tokens otherwise this is the result of "
"misconfiguration."
msgstr ""

#: keystone/exception.py:136
msgid "(Disable debug mode to suppress these details.)"
msgstr ""

#: keystone/exception.py:141
#, python-format
msgid "%(message)s %(amendment)s"
msgstr ""

#: keystone/exception.py:149
msgid "The request you have made requires authentication."
msgstr ""

#: keystone/exception.py:155
msgid "Authentication plugin error."
msgstr ""

#: keystone/exception.py:163
#, python-format
msgid "Unable to find valid groups while using mapping %(mapping_id)s"
msgstr ""

#: keystone/exception.py:168
msgid "Attempted to authenticate with an unsupported method."
msgstr ""

#: keystone/exception.py:176
msgid "Additional authentications steps required."
msgstr ""

#: keystone/exception.py:184
msgid "You are not authorized to perform the requested action."
msgstr ""

#: keystone/exception.py:191
#, python-format
msgid "You are not authorized to perform the requested action: %(action)s"
msgstr ""

#: keystone/exception.py:196
#, python-format
msgid ""
"Could not change immutable attribute(s) '%(attributes)s' in target "
"%(target)s"
msgstr ""

#: keystone/exception.py:201
#, python-format
msgid ""
"Group membership across backend boundaries is not allowed, group in "
"question is %(group_id)s, user is %(user_id)s"
msgstr ""

#: keystone/exception.py:207
#, python-format
msgid "Could not find: %(target)s"
msgstr ""

#: keystone/exception.py:213
#, python-format
msgid "Could not find endpoint: %(endpoint_id)s"
msgstr ""

#: keystone/exception.py:220
msgid "An unhandled exception has occurred: Could not find metadata."
msgstr ""

#: keystone/exception.py:225
#, python-format
msgid "Could not find policy: %(policy_id)s"
msgstr ""

#: keystone/exception.py:229
#, python-format
msgid "Could not find role: %(role_id)s"
msgstr ""

#: keystone/exception.py:233
#, python-format
msgid "Could not find region: %(region_id)s"
msgstr ""

#: keystone/exception.py:237
#, python-format
msgid "Could not find service: %(service_id)s"
msgstr ""

#: keystone/exception.py:241
#, python-format
msgid "Could not find domain: %(domain_id)s"
msgstr ""

#: keystone/exception.py:245
#, python-format
msgid "Could not find project: %(project_id)s"
msgstr ""

#: keystone/exception.py:249
#, python-format
msgid "Could not find token: %(token_id)s"
msgstr ""

#: keystone/exception.py:253
#, python-format
msgid "Could not find user: %(user_id)s"
msgstr ""

#: keystone/exception.py:257
#, python-format
msgid "Could not find group: %(group_id)s"
msgstr ""

#: keystone/exception.py:261
#, python-format
msgid "Could not find mapping: %(mapping_id)s"
msgstr ""

#: keystone/exception.py:265
#, python-format
msgid "Could not find trust: %(trust_id)s"
msgstr ""

#: keystone/exception.py:269
#, python-format
msgid "No remaining uses for trust: %(trust_id)s"
msgstr ""

#: keystone/exception.py:273
#, python-format
msgid "Could not find credential: %(credential_id)s"
msgstr ""

#: keystone/exception.py:277
#, python-format
msgid "Could not find version: %(version)s"
msgstr ""

#: keystone/exception.py:281
#, python-format
msgid "Could not find Identity Provider: %(idp_id)s"
msgstr ""

#: keystone/exception.py:285
#, python-format
msgid ""
"Could not find federated protocol %(protocol_id)s for Identity Provider: "
"%(idp_id)s"
msgstr ""

#: keystone/exception.py:296
#, python-format
msgid "Conflict occurred attempting to store %(type)s - %(details)s"
msgstr ""

#: keystone/exception.py:303
msgid "Request is too large."
msgstr ""

#: keystone/exception.py:310
msgid "An unexpected error prevented the server from fulfilling your request."
msgstr ""

#: keystone/exception.py:313
#, python-format
msgid ""
"An unexpected error prevented the server from fulfilling your request: "
"%(exception)s"
msgstr ""

#: keystone/exception.py:336
msgid ""
"Expected signing certificates are not available on the server. Please "
"check Keystone configuration."
msgstr ""

#: keystone/exception.py:342
#, python-format
msgid "Malformed endpoint URL (%(endpoint)s), see ERROR log for details."
msgstr ""

#: keystone/exception.py:347
#, python-format
msgid ""
"Group %(group_id)s returned by mapping %(mapping_id)s was not found in "
"the backend."
msgstr ""

#: keystone/exception.py:352
msgid "The action you have requested has not been implemented."
msgstr ""

#: keystone/exception.py:359
msgid "The service you have requested is no longer available on this server."
msgstr ""

#: keystone/exception.py:366
#, python-format
msgid "The Keystone configuration file %(config_file)s could not be found."
msgstr ""

#: keystone/exception.py:372
#, python-format
msgid ""
"%(mod_name)s doesn't provide database migrations. The migration "
"repository path at %(path)s doesn't exist or isn't a directory."
msgstr ""

#: keystone/notifications.py:124
#, python-format
msgid "%(event)s is not a valid notification event, must be one of: %(actions)s"
msgstr ""

#: keystone/notifications.py:133
#, python-format
msgid "Method not callable: %s"
msgstr ""

#: keystone/notifications.py:141
#, python-format
msgid "Callback: `%(callback)s` subscribed to event `%(event)s`."
msgstr ""

#: keystone/notifications.py:225
#, python-format
msgid "Failed to send %(res_id)s %(event_type)s notification"
msgstr ""

#: keystone/notifications.py:309
#, python-format
msgid "Failed to send %(action)s %(event_type)s notification"
msgstr ""

#: keystone/assignment/controllers.py:70
#, python-format
msgid "Authentication failed: %s"
msgstr ""

#: keystone/assignment/controllers.py:104
#: keystone/assignment/controllers.py:218 keystone/identity/controllers.py:67
msgid "Name field is required and cannot be empty"
msgstr ""

#: keystone/assignment/controllers.py:159
msgid "Marker could not be found"
msgstr ""

#: keystone/assignment/controllers.py:170
msgid "Invalid limit value"
msgstr ""

#: keystone/assignment/controllers.py:473
msgid "Specify a domain or project, not both"
msgstr ""

#: keystone/assignment/controllers.py:478
msgid "Specify a user or group, not both"
msgstr ""

#: keystone/assignment/controllers.py:692
#, python-format
msgid ""
"Group %(group)s not found for role-assignment - %(target)s with Role: "
"%(role)s"
msgstr ""

#: keystone/assignment/core.py:94 keystone/token/core.py:72
#: keystone/token/core.py:88
#, python-format
msgid "Domain is disabled: %s"
msgstr ""

#: keystone/assignment/core.py:105
#, python-format
msgid "Project is disabled: %s"
msgstr ""

#: keystone/assignment/core.py:248
#, python-format
msgid "Creating the default role %s because it does not exist."
msgstr ""

#: keystone/assignment/core.py:347
msgid "delete the default domain"
msgstr ""

#: keystone/assignment/core.py:358
msgid "cannot delete a domain that is enabled, please disable it first."
msgstr ""

#: keystone/assignment/core.py:568
#, python-format
msgid "Project (%s)"
msgstr ""

#: keystone/assignment/core.py:570
#, python-format
msgid "Domain (%s)"
msgstr ""

#: keystone/assignment/core.py:572
msgid "Unknown Target"
msgstr ""

#: keystone/assignment/core.py:1032 keystone/common/controller.py:281
#: keystone/identity/core.py:309
#, python-format
msgid "Expected dict or list: %s"
msgstr ""

#: keystone/assignment/backends/kvs.py:246
#: keystone/assignment/backends/ldap.py:549
#: keystone/assignment/backends/sql.py:383
#, python-format
msgid "Cannot remove role that has not been granted, %s"
msgstr ""

#: keystone/assignment/backends/ldap.py:119
msgid "Domain metadata not supported by LDAP"
msgstr ""

#: keystone/assignment/backends/ldap.py:212
#: keystone/assignment/backends/ldap.py:256 keystone/catalog/core.py:86
#: keystone/common/ldap/core.py:1339 keystone/identity/backends/kvs.py:114
#: keystone/identity/backends/kvs.py:219
#, python-format
msgid "Duplicate ID, %s."
msgstr ""

#: keystone/assignment/backends/ldap.py:220 keystone/common/ldap/core.py:1329
#: keystone/identity/backends/kvs.py:122 keystone/identity/backends/kvs.py:149
#: keystone/identity/backends/kvs.py:226 keystone/identity/backends/kvs.py:254
#, python-format
msgid "Duplicate name, %s."
msgstr ""

#: keystone/assignment/backends/ldap.py:258
#: keystone/assignment/backends/ldap.py:266
#: keystone/assignment/backends/ldap.py:270
msgid "Domains are read-only against LDAP"
msgstr ""

#: keystone/assignment/backends/ldap.py:317
#: keystone/assignment/backends/sql.py:145
msgid "Inherited roles can only be assigned to domains"
msgstr ""

#: keystone/assignment/backends/ldap.py:526
#, python-format
msgid "User %(user_id)s already has role %(role_id)s in tenant %(tenant_id)s"
msgstr ""

#: keystone/assignment/backends/ldap.py:532
#, python-format
msgid "Role %s not found"
msgstr ""

#: keystone/assignment/backends/ldap.py:643
#, python-format
msgid "Cannot duplicate name %s"
msgstr ""

#: keystone/assignment/backends/sql.py:132
#, python-format
msgid ""
"Unexpected combination of grant attributes - User, Group, Project, "
"Domain: %s"
msgstr ""

#: keystone/assignment/backends/sql.py:301
msgid "Must specify either domain or project"
msgstr ""

#: keystone/assignment/backends/sql.py:404
#, python-format
msgid "Unexpected assignment type encountered, %s"
msgstr ""

#: keystone/auth/controllers.py:58
#, python-format
msgid ""
"Cannot load an auth-plugin by class-name without a \"method\" attribute "
"defined: %s"
msgstr ""

#: keystone/auth/controllers.py:66
#, python-format
msgid "Driver requested method %(req)s does not match plugin name %(plugin)s."
msgstr ""

#: keystone/auth/controllers.py:71
#, python-format
msgid "Auth Plugin %s does not have a \"method\" attribute."
msgstr ""

#: keystone/auth/controllers.py:75
#, python-format
msgid ""
"Auth plugin %(plugin)s is requesting previously registered method "
"%(method)s"
msgstr ""

#: keystone/auth/controllers.py:119
#, python-format
msgid ""
"Unable to reconcile identity attribute %(attribute)s as it has "
"conflicting values %(new)s and %(old)s"
msgstr ""

#: keystone/auth/controllers.py:336
msgid "Scoping to both domain and project is not allowed"
msgstr ""

#: keystone/auth/controllers.py:339
msgid "Scoping to both domain and trust is not allowed"
msgstr ""

#: keystone/auth/controllers.py:342
msgid "Scoping to both project and trust is not allowed"
msgstr ""

#: keystone/auth/controllers.py:442
#, python-format
msgid ""
"User %(user_id)s doesn't have access to default project %(project_id)s. "
"The token will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:449
#, python-format
msgid ""
"User %(user_id)s's default project %(project_id)s is disabled. The token "
"will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:458
#, python-format
msgid ""
"User %(user_id)s's default project %(project_id)s not found. The token "
"will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:498
msgid "User not found"
msgstr ""

#: keystone/auth/plugins/external.py:46
msgid "No authenticated user"
msgstr ""

#: keystone/auth/plugins/external.py:56
#, python-format
msgid "Unable to lookup user %s"
msgstr ""

#: keystone/auth/plugins/external.py:107
msgid "auth_type is not Negotiate"
msgstr ""

#: keystone/auth/plugins/oauth1.py:38
#, python-format
msgid "%s not supported"
msgstr ""

#: keystone/auth/plugins/oauth1.py:56
msgid "Access token is expired"
msgstr ""

#: keystone/auth/plugins/oauth1.py:70
msgid "Could not validate the access token"
msgstr ""

#: keystone/auth/plugins/password.py:134
msgid "Invalid username or password"
msgstr ""

#: keystone/catalog/controllers.py:157
msgid "A project-scoped token is required to produce a service catalog."
msgstr ""

#: keystone/catalog/controllers.py:185
#, python-format
msgid "Conflicting region IDs specified: \"%(url_id)s\" != \"%(ref_id)s\""
msgstr ""

#: keystone/catalog/controllers.py:237 keystone/catalog/controllers.py:296
#: keystone/identity/controllers.py:70
msgid "Enabled field must be a boolean"
msgstr ""

#: keystone/catalog/core.py:45
#, python-format
msgid "Malformed endpoint - %(url)r is not a string"
msgstr ""

#: keystone/catalog/core.py:49
#, python-format
msgid "Malformed endpoint %(url)s - unknown key %(keyerror)s"
msgstr ""

#: keystone/catalog/core.py:54
#, python-format
msgid ""
"Malformed endpoint '%(url)s'. The following type error occurred during "
"string substitution: %(typeerror)s"
msgstr ""

#: keystone/catalog/core.py:60
#, python-format
msgid ""
"Malformed endpoint %s - incomplete format (are you missing a type "
"notifier ?)"
msgstr ""

#: keystone/catalog/backends/templated.py:106
#, python-format
msgid "Unable to open template file %s"
msgstr ""

#: keystone/common/authorization.py:56
msgid "RBAC: Invalid user data in v3 token"
msgstr ""

#: keystone/common/authorization.py:100
msgid "RBAC: Invalid user data in v2 token"
msgstr ""

#: keystone/common/base64utils.py:205 keystone/common/base64utils.py:278
#: keystone/common/base64utils.py:332
msgid "pad must be single character"
msgstr ""

#: keystone/common/base64utils.py:211
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before 2nd to last char"
msgstr ""

#: keystone/common/base64utils.py:215
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before non-pad last char"
msgstr ""

#: keystone/common/base64utils.py:221
#, python-format
msgid "text is not a multiple of 4, but contains pad \"%s\""
msgstr ""

#: keystone/common/base64utils.py:240 keystone/common/base64utils.py:261
msgid "padded base64url text must be multiple of 4 characters"
msgstr ""

#: keystone/common/controller.py:74 keystone/middleware/core.py:271
msgid "RBAC: Invalid token"
msgstr ""

#: keystone/common/controller.py:103 keystone/common/controller.py:194
#: keystone/common/controller.py:647
msgid "RBAC: Bypassing authorization"
msgstr ""

#: keystone/common/controller.py:551
msgid "Cannot change Domain ID"
msgstr ""

#: keystone/common/controller.py:578
msgid "domain_id is required as part of entity"
msgstr ""

#: keystone/common/controller.py:580 keystone/common/controller.py:611
msgid "Invalid token found while getting domain ID for list request"
msgstr ""

#: keystone/common/controller.py:588
msgid "No domain information specified as part of list request"
msgstr ""

#: keystone/common/controller.py:609
msgid "A domain-scoped token must be used"
msgstr ""

#: keystone/common/dependency.py:83
msgid "event_callbacks must be a dict"
msgstr ""

#: keystone/common/dependency.py:88
#, python-format
msgid "event_callbacks[%s] must be a dict"
msgstr ""

#: keystone/common/pemutils.py:223
#, python-format
msgid "unknown pem_type \"%(pem_type)s\", valid types are: %(valid_pem_types)s"
msgstr ""

#: keystone/common/pemutils.py:242
#, python-format
msgid ""
"unknown pem header \"%(pem_header)s\", valid headers are: "
"%(valid_pem_headers)s"
msgstr ""

#: keystone/common/pemutils.py:298
#, python-format
msgid "failed to find end matching \"%s\""
msgstr ""

#: keystone/common/pemutils.py:302
#, python-format
msgid ""
"beginning & end PEM headers do not match (%(begin_pem_header)s!= "
"%(end_pem_header)s)"
msgstr ""

#: keystone/common/pemutils.py:377
#, python-format
msgid "unknown pem_type: \"%s\""
msgstr ""

#: keystone/common/pemutils.py:389
#, python-format
msgid ""
"failed to base64 decode %(pem_type)s PEM at position%(position)d: "
"%(err_msg)s"
msgstr ""

#: keystone/common/serializer.py:203
msgid "Multiple truncation attributes found"
msgstr ""

#: keystone/common/utils.py:98
#, python-format
msgid "Truncating user password to %d characters."
msgstr ""

#: keystone/common/utils.py:196 keystone/credential/controllers.py:42
msgid "Invalid blob in credential"
msgstr ""

#: keystone/common/utils.py:275
msgid ""
"Error setting up the debug environment. Verify that the option --debug-"
"url has the format <host>:<port> and that a debugger processes is "
"listening on that port."
msgstr ""

#: keystone/common/wsgi.py:67
msgid "No bind information present in token"
msgstr ""

#: keystone/common/wsgi.py:71
#, python-format
msgid "Named bind mode %s not in bind information"
msgstr ""

#: keystone/common/wsgi.py:78
msgid "Kerberos credentials required and not present"
msgstr ""

#: keystone/common/wsgi.py:82
msgid "Kerberos credentials do not match those in bind"
msgstr ""

#: keystone/common/wsgi.py:85
msgid "Kerberos bind authentication successful"
msgstr ""

#: keystone/common/wsgi.py:92
#, python-format
msgid "Couldn't verify unknown bind: {%(bind_type)s: %(identifier)s}"
msgstr ""

#: keystone/common/wsgi.py:215
#, python-format
msgid "Authorization failed. %(exception)s from %(remote_addr)s"
msgstr ""

#: keystone/common/wsgi.py:302
#, python-format
msgid "%s field is required and cannot be empty"
msgstr ""

#: keystone/common/wsgi.py:314
#, python-format
msgid "%s field(s) cannot be empty"
msgstr ""

#: keystone/common/wsgi.py:332
msgid "Invalid token in _get_trust_id_for_request"
msgstr ""

#: keystone/common/wsgi.py:528
msgid "The resource could not be found."
msgstr ""

#: keystone/common/cache/core.py:96
#, python-format
msgid ""
"Unable to build cache config-key. Expected format \"<argname>:<value>\". "
"Skipping unknown format: %s"
msgstr ""

#: keystone/common/cache/core.py:119
msgid "region not type dogpile.cache.CacheRegion"
msgstr ""

#: keystone/common/cache/backends/mongo.py:231
msgid "db_hosts value is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:236
msgid "database db_name is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:241
msgid "cache_collection name is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:252
msgid "integer value expected for w (write concern attribute)"
msgstr ""

#: keystone/common/cache/backends/mongo.py:260
msgid "replicaset_name required when use_replica is True"
msgstr ""

#: keystone/common/cache/backends/mongo.py:275
msgid "integer value expected for mongo_ttl_seconds"
msgstr ""

#: keystone/common/cache/backends/mongo.py:301
msgid "no ssl support available"
msgstr ""

#: keystone/common/cache/backends/mongo.py:310
#, python-format
msgid ""
"Invalid ssl_cert_reqs value of %s, must be one of \"NONE\", \"OPTIONAL\","
" \"REQUIRED\""
msgstr ""

#: keystone/common/cache/backends/mongo.py:403
#, python-format
msgid ""
"TTL index already exists on db collection <%(c_name)s>, remove index "
"<%(indx_name)s> first to make updated mongo_ttl_seconds value to be  "
"effective"
msgstr ""

#: keystone/common/environment/eventlet_server.py:93
msgid "Server can only listen once."
msgstr ""

#: keystone/common/environment/eventlet_server.py:95
#, python-format
msgid "Starting %(arg0)s on %(host)s:%(port)s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:171
msgid "Server error"
msgstr ""

#: keystone/common/kvs/core.py:69
#, python-format
msgid "Lock Timeout occurred for key, %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:104
#, python-format
msgid "KVS region %s is already configured. Cannot reconfigure."
msgstr ""

#: keystone/common/kvs/core.py:128
#, python-format
msgid "%s is not a dogpile.proxy.ProxyBackend"
msgstr ""

#: keystone/common/kvs/core.py:132
#, python-format
msgid "Adding proxy '%(proxy)s' to KVS %(name)s."
msgstr ""

#: keystone/common/kvs/core.py:139
#, python-format
msgid "Key Value Store not configured: %s"
msgstr ""

#: keystone/common/kvs/core.py:182
#, python-format
msgid "Using %(func)s as KVS region %(name)s key_mangler"
msgstr ""

#: keystone/common/kvs/core.py:192
msgid "`key_mangler` option must be a function reference"
msgstr ""

#: keystone/common/kvs/core.py:194
#, python-format
msgid "Using default dogpile sha1_mangle_key as KVS region %s key_mangler"
msgstr ""

#: keystone/common/kvs/core.py:204
#, python-format
msgid "KVS region %s key_mangler disabled."
msgstr ""

#: keystone/common/kvs/core.py:346
#, python-format
msgid "Lock key must match target key: %(lock)s != %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:350
msgid "Must be called within an active lock context."
msgstr ""

#: keystone/common/kvs/core.py:395
#, python-format
msgid "KVS lock released (timeout reached) for: %s"
msgstr ""

#: keystone/common/kvs/backends/memcached.py:70
#, python-format
msgid "Maximum lock attempts on %s occurred."
msgstr ""

#: keystone/common/kvs/backends/memcached.py:109
#, python-format
msgid ""
"Backend `%(driver)s` is not a valid memcached backend. Valid drivers: "
"%(driver_list)s"
msgstr ""

#: keystone/common/kvs/backends/memcached.py:180
msgid "`key_mangler` functions must be callable."
msgstr ""

#: keystone/common/ldap/core.py:176
#, python-format
msgid "Invalid LDAP deref option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:186
#, python-format
msgid "Invalid LDAP TLS certs option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:198
#, python-format
msgid "Invalid LDAP scope: %(scope)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:572
msgid "Invalid TLS / LDAPS combination"
msgstr ""

#: keystone/common/ldap/core.py:576
#, python-format
msgid "Invalid LDAP TLS_AVAIL option: %s. TLS not available"
msgstr ""

#: keystone/common/ldap/core.py:586
#, python-format
msgid "tls_cacertfile %s not found or is not a file"
msgstr ""

#: keystone/common/ldap/core.py:598
#, python-format
msgid "tls_cacertdir %s not found or is not a directory"
msgstr ""

#: keystone/common/ldap/core.py:988
msgid ""
"LDAP Server does not support paging. Disable paging in keystone.conf to "
"avoid this message."
msgstr ""

#: keystone/common/ldap/core.py:1184
#, python-format
msgid ""
"Invalid additional attribute mapping: \"%s\". Format must be "
"<ldap_attribute>:<keystone_attribute>"
msgstr ""

#: keystone/common/ldap/core.py:1308
#, python-format
msgid "LDAP %s create"
msgstr ""

#: keystone/common/ldap/core.py:1313
#, python-format
msgid "LDAP %s update"
msgstr ""

#: keystone/common/ldap/core.py:1318
#, python-format
msgid "LDAP %s delete"
msgstr ""

#: keystone/common/ldap/core.py:1461
#, python-format
msgid "Cannot change %(option_name)s %(attr)s"
msgstr ""

#: keystone/common/ldap/core.py:1528
#, python-format
msgid "Member %(member)s is already a member of group %(group)s"
msgstr ""

#: keystone/common/ldap/core.py:1586
#, python-format
msgid ""
"When deleting entries for %(search_base)s, could not delete nonexistent "
"entries %(entries)s%(dots)s"
msgstr ""

#: keystone/common/sql/core.py:219
msgid ""
"Cannot truncate a driver call without hints list as first parameter after"
" self "
msgstr ""

#: keystone/common/sql/core.py:400
msgid "Duplicate Entry"
msgstr ""

#: keystone/common/sql/core.py:416
#, python-format
msgid "An unexpected error occurred when trying to store %s"
msgstr ""

#: keystone/common/sql/migration_helpers.py:184
#: keystone/common/sql/migration_helpers.py:223
#, python-format
msgid "%s extension does not exist."
msgstr ""

#: keystone/common/validation/validators.py:54
#, python-format
msgid "Invalid input for field '%(path)s'. The value is '%(value)s'."
msgstr ""

#: keystone/contrib/ec2/controllers.py:314
msgid "Token belongs to another user"
msgstr ""

#: keystone/contrib/ec2/controllers.py:342
msgid "Credential belongs to another user"
msgstr ""

#: keystone/contrib/endpoint_filter/backends/sql.py:46
#, python-format
msgid "Endpoint %(endpoint_id)s not found in project %(project_id)s"
msgstr ""

#: keystone/contrib/example/core.py:64 keystone/contrib/example/core.py:73
#, python-format
msgid ""
"Received the following notification: service %(service)s, resource_type: "
"%(resource_type)s, operation %(operation)s payload %(payload)s"
msgstr ""

#: keystone/contrib/federation/utils.py:122
msgid "Federation token is expired"
msgstr ""

#: keystone/contrib/federation/utils.py:225
msgid "Could not map user"
msgstr ""

#: keystone/contrib/federation/utils.py:254
#, python-format
msgid "Ignoring user name %s"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:79
msgid "Cannot change consumer secret"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:111
msgid "Cannot list request tokens with a token issued via delegation."
msgstr ""

#: keystone/contrib/oauth1/controllers.py:170
#: keystone/contrib/oauth1/backends/sql.py:267
msgid "User IDs do not match"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:177
msgid "Could not find role"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:220
msgid "Invalid signature"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:269
#: keystone/contrib/oauth1/controllers.py:345
msgid "Request token is expired"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:283
msgid "There should not be any non-oauth parameters"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:287
msgid "provided consumer key does not match stored consumer key"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:291
msgid "provided verifier does not match stored verifier"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:295
msgid "provided request key does not match stored request key"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:299
msgid "Request Token does not have an authorizing user id"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:334
msgid "Cannot authorize a request token with a token issued via delegation."
msgstr ""

#: keystone/contrib/oauth1/controllers.py:361
msgid "authorizing user does not have role required"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:374
msgid "User is not a member of the requested project"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:88
msgid "Consumer not found"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:183
msgid "Request token not found"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:247
msgid "Access token not found"
msgstr ""

#: keystone/contrib/revoke/controllers.py:32
#, python-format
msgid "invalid date format %s"
msgstr ""

#: keystone/contrib/revoke/core.py:173 keystone/token/provider.py:146
#: keystone/token/provider.py:167 keystone/token/provider.py:255
#: keystone/token/provider.py:262 keystone/token/providers/common.py:612
msgid "Failed to validate token"
msgstr ""

#: keystone/identity/controllers.py:96
msgid "Enabled field should be a boolean"
msgstr ""

#: keystone/identity/controllers.py:137
#, python-format
msgid "Unable to remove user %(user)s from %(tenant)s."
msgstr ""

#: keystone/identity/controllers.py:156
#, python-format
msgid "Unable to add user %(user)s to %(tenant)s."
msgstr ""

#: keystone/identity/core.py:101
#, python-format
msgid "Invalid domain name (%s) found in config file name"
msgstr ""

#: keystone/identity/core.py:125
#, python-format
msgid "Unable to locate domain config directory: %s"
msgstr ""

#: keystone/identity/core.py:200 keystone/identity/backends/kvs.py:69
#: keystone/identity/backends/kvs.py:71 keystone/identity/backends/ldap.py:61
#: keystone/identity/backends/ldap.py:63 keystone/identity/backends/ldap.py:69
#: keystone/identity/backends/ldap.py:71 keystone/identity/backends/sql.py:101
#: keystone/identity/backends/sql.py:103
msgid "Invalid user / password"
msgstr ""

#: keystone/identity/core.py:573 keystone/token/core.py:64
#, python-format
msgid "User is disabled: %s"
msgstr ""

#: keystone/identity/core.py:614
msgid "Cannot change user ID"
msgstr ""

#: keystone/identity/backends/kvs.py:173 keystone/identity/backends/kvs.py:182
msgid "User not found in group"
msgstr ""

#: keystone/identity/backends/ldap.py:101
msgid "Cannot change user name"
msgstr ""

#: keystone/identity/backends/ldap.py:179 keystone/identity/backends/sql.py:185
#: keystone/identity/backends/sql.py:203
#, python-format
msgid "User '%(user_id)s' not found in group '%(group_id)s'"
msgstr ""

#: keystone/identity/backends/ldap.py:304
#, python-format
msgid "User %(user_id)s is already a member of group %(group_id)s"
msgstr ""

#: keystone/middleware/core.py:281
msgid "Auth context already exists in the request environment"
msgstr ""

#: keystone/models/token_model.py:57
msgid "Found invalid token: scoped to both project and domain."
msgstr ""

#: keystone/openstack/common/gettextutils.py:301
msgid "Message objects do not support addition."
msgstr ""

#: keystone/openstack/common/gettextutils.py:311
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: keystone/openstack/common/lockutils.py:101
#, python-format
msgid "Unable to acquire lock on `%(filename)s` due to %(exception)s"
msgstr ""

#: keystone/openstack/common/log.py:276
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: keystone/openstack/common/log.py:385
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: keystone/openstack/common/log.py:444
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: keystone/openstack/common/log.py:687
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: keystone/openstack/common/policy.py:96
msgid "The JSON file that defines policies."
msgstr ""

#: keystone/openstack/common/policy.py:99
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: keystone/openstack/common/policy.py:114
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: keystone/openstack/common/policy.py:208
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: keystone/openstack/common/strutils.py:114
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: keystone/openstack/common/strutils.py:219
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: keystone/openstack/common/strutils.py:228
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: keystone/openstack/common/versionutils.py:78
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: keystone/openstack/common/versionutils.py:82
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: keystone/tests/core.py:145
#, python-format
msgid "Failed to checkout %s"
msgstr ""

#: keystone/token/controllers.py:384
#, python-format
msgid "User %(u_id)s is unauthorized for tenant %(t_id)s"
msgstr ""

#: keystone/token/controllers.py:401 keystone/token/controllers.py:404
msgid "Token does not belong to specified tenant."
msgstr ""

#: keystone/token/core.py:79
#, python-format
msgid "Tenant is disabled: %s"
msgstr ""

#: keystone/token/provider.py:101
msgid ""
"[signing] token_format is deprecated. Please change to setting the "
"[token] provider configuration value instead"
msgstr ""

#: keystone/token/provider.py:109
msgid ""
"Unrecognized keystone.conf [signing] token_format: expected either 'UUID'"
" or 'PKI'"
msgstr ""

#: keystone/token/provider.py:253
#, python-format
msgid "Unexpected error or malformed token determining token expiry: %s"
msgstr ""

#: keystone/token/persistence/backends/kvs.py:55
msgid ""
"It is recommended to only use the base key-value-store implementation for"
" the token driver for testing purposes.  Please use "
"keystone.token.backends.memcache.Token or "
"keystone.token.backends.sql.Token instead."
msgstr ""

#: keystone/token/persistence/backends/kvs.py:130
#, python-format
msgid "Unknown token version %s"
msgstr ""

#: keystone/token/persistence/backends/kvs.py:203
#, python-format
msgid "Token `%s` is expired, not adding to the revocation list."
msgstr ""

#: keystone/token/persistence/backends/kvs.py:223
#, python-format
msgid ""
"Reinitializing revocation list due to error in loading revocation list "
"from backend.  Expected `list` type got `%(type)s`. Old revocation list "
"data: %(list)r"
msgstr ""

#: keystone/token/persistence/backends/kvs.py:237
#, python-format
msgid ""
"Removing `%s` from revocation list due to invalid expires data in "
"revocation list."
msgstr ""

#: keystone/token/providers/common.py:182
#: keystone/token/providers/common.py:285
#, python-format
msgid "User %(user_id)s has no access to project %(project_id)s"
msgstr ""

#: keystone/token/providers/common.py:187
#: keystone/token/providers/common.py:290
#, python-format
msgid "User %(user_id)s has no access to domain %(domain_id)s"
msgstr ""

#: keystone/token/providers/common.py:212
msgid "Trustor is disabled."
msgstr ""

#: keystone/token/providers/common.py:276
msgid "Trustee has no delegated roles."
msgstr ""

#: keystone/token/providers/common.py:338
msgid "User is not a trustee."
msgstr ""

#: keystone/token/providers/common.py:435
msgid "Oauth is disabled."
msgstr ""

#: keystone/token/providers/common.py:537
msgid "Non-default domain is not supported"
msgstr ""

#: keystone/token/providers/common.py:545
msgid "Domain scoped token is not supported"
msgstr ""

#: keystone/token/providers/pki.py:45
msgid "Unable to sign token"
msgstr ""

#: keystone/token/providers/pki.py:46 keystone/token/providers/pkiz.py:29
msgid "Unable to sign token."
msgstr ""

#: keystone/trust/controllers.py:132
msgid "Cannot create a trust with a token issued via delegation."
msgstr ""

#: keystone/trust/controllers.py:161
msgid "The authenticated user should match the trustor."
msgstr ""

#: keystone/trust/controllers.py:166
msgid "At least one role should be specified."
msgstr ""

#: keystone/trust/core.py:58
msgid "remaining_uses must be a positive integer or null."
msgstr ""

