# Hindi translations for keystone.
# Copyright (C) 2013 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version:  Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2013-12-28 06:00+0000\n"
"PO-Revision-Date: 2013-08-30 04:19+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Hindi "
"(http://www.transifex.com/projects/p/openstack/language/hi/)\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: keystone/clean.py:23
#, python-format
msgid "%s cannot be empty."
msgstr ""

#: keystone/clean.py:25
#, python-format
msgid "%(property_name)s cannot be less than %(min_length)s characters."
msgstr ""

#: keystone/clean.py:30
#, python-format
msgid "%(property_name)s should not be greater than %(max_length)s characters."
msgstr ""

#: keystone/clean.py:39
#, python-format
msgid "%(property_name)s is not a %(display_expected_type)s"
msgstr ""

#: keystone/cli.py:81 keystone/cli.py:117
msgid "This extension does not provide migrations."
msgstr ""

#: keystone/exception.py:50
msgid "missing exception kwargs (programmer error)"
msgstr ""

#: keystone/exception.py:80
#, python-format
msgid ""
"Expecting to find %(attribute)s in %(target)s. The server could not "
"comply with the request since it is either malformed or otherwise "
"incorrect. The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:89
msgid ""
"Timestamp not in expected format. The server could not comply with the "
"request since it is either malformed or otherwise incorrect. The client "
"is assumed to be in error."
msgstr ""

#: keystone/exception.py:98
#, python-format
msgid ""
"String length exceeded.The length of string '%(string)s' exceeded the "
"limit of column %(type)s(CHAR(%(length)d))."
msgstr ""

#: keystone/exception.py:104
#, python-format
msgid ""
"Request attribute %(attribute)s must be less than or equal to %(size)i. "
"The server could not comply with the request because the attribute size "
"is invalid (too large). The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:125
msgid "The request you have made requires authentication."
msgstr ""

#: keystone/exception.py:131
msgid "Authentication plugin error."
msgstr ""

#: keystone/exception.py:139
msgid "Attempted to authenticate with an unsupported method."
msgstr ""

#: keystone/exception.py:147
msgid "Additional authentications steps required."
msgstr ""

#: keystone/exception.py:155
msgid "You are not authorized to perform the requested action."
msgstr ""

#: keystone/exception.py:162
#, python-format
msgid "You are not authorized to perform the requested action, %(action)s."
msgstr ""

#: keystone/exception.py:167
#, python-format
msgid "Could not find, %(target)s."
msgstr ""

#: keystone/exception.py:173
#, python-format
msgid "Could not find endpoint, %(endpoint_id)s."
msgstr ""

#: keystone/exception.py:180
msgid "An unhandled exception has occurred: Could not find metadata."
msgstr ""

#: keystone/exception.py:185
#, python-format
msgid "Could not find policy, %(policy_id)s."
msgstr ""

#: keystone/exception.py:189
#, python-format
msgid "Could not find role, %(role_id)s."
msgstr ""

#: keystone/exception.py:193
#, python-format
msgid "Could not find service, %(service_id)s."
msgstr ""

#: keystone/exception.py:197
#, python-format
msgid "Could not find domain, %(domain_id)s."
msgstr ""

#: keystone/exception.py:201
#, python-format
msgid "Could not find project, %(project_id)s."
msgstr ""

#: keystone/exception.py:205
#, python-format
msgid "Could not find token, %(token_id)s."
msgstr ""

#: keystone/exception.py:209
#, python-format
msgid "Could not find user, %(user_id)s."
msgstr ""

#: keystone/exception.py:213
#, python-format
msgid "Could not find group, %(group_id)s."
msgstr ""

#: keystone/exception.py:217
#, python-format
msgid "Could not find trust, %(trust_id)s."
msgstr ""

#: keystone/exception.py:221
#, python-format
msgid "Could not find credential, %(credential_id)s."
msgstr ""

#: keystone/exception.py:225
#, python-format
msgid "Could not find version, %(version)s."
msgstr ""

#: keystone/exception.py:229
#, python-format
msgid "Conflict occurred attempting to store %(type)s. %(details)s"
msgstr ""

#: keystone/exception.py:236
msgid "Request is too large."
msgstr ""

#: keystone/exception.py:242
#, python-format
msgid ""
"An unexpected error prevented the server from fulfilling your request. "
"%(exception)s"
msgstr ""

#: keystone/exception.py:249
#, python-format
msgid "Malformed endpoint URL (%(endpoint)s), see ERROR log for details."
msgstr ""

#: keystone/exception.py:254
msgid "The action you have requested has not been implemented."
msgstr ""

#: keystone/exception.py:261
#, python-format
msgid "The Keystone configuration file %(config_file)s could not be found."
msgstr ""

#: keystone/notifications.py:97
#, python-format
msgid "Failed to send %(res_id)s %(event_type)s notification"
msgstr ""

#: keystone/assignment/controllers.py:70
#, python-format
msgid "Authentication failed: %s"
msgstr ""

#: keystone/assignment/controllers.py:104
#: keystone/assignment/controllers.py:217 keystone/identity/controllers.py:130
msgid "Name field is required and cannot be empty"
msgstr ""

#: keystone/assignment/controllers.py:158
msgid "Marker could not be found"
msgstr ""

#: keystone/assignment/controllers.py:169
msgid "Invalid limit value"
msgstr ""

#: keystone/assignment/controllers.py:612
msgid "Specify a domain or project, not both"
msgstr ""

#: keystone/assignment/controllers.py:617
msgid "Specify a user or group, not both"
msgstr ""

#: keystone/assignment/controllers.py:847
#, python-format
msgid ""
"Group %(group)s not found for role-assignment - %(target)s with Role: "
"%(role)s"
msgstr ""

#: keystone/assignment/core.py:224
#, python-format
msgid "Creating the default role %s because it does not exist."
msgstr ""

#: keystone/assignment/core.py:683 keystone/identity/core.py:256
#: keystone/identity/core.py:268
#, python-format
msgid "Expected dict or list: %s"
msgstr ""

#: keystone/assignment/backends/kvs.py:140
#: keystone/assignment/backends/ldap.py:449
#: keystone/assignment/backends/sql.py:333
#: keystone/assignment/backends/sql.py:340
#, python-format
msgid "Cannot remove role that has not been granted, %s"
msgstr ""

#: keystone/assignment/backends/ldap.py:428
#, python-format
msgid "Role %s not found"
msgstr ""

#: keystone/assignment/backends/sql.py:104
msgid "Inherited roles can only be assigned to domains"
msgstr ""

#: keystone/auth/controllers.py:75
#, python-format
msgid "Project is disabled: %s"
msgstr ""

#: keystone/auth/controllers.py:81 keystone/auth/plugins/password.py:42
#: keystone/token/core.py:77 keystone/token/core.py:93
#, python-format
msgid "Domain is disabled: %s"
msgstr ""

#: keystone/auth/controllers.py:87 keystone/auth/plugins/password.py:48
#: keystone/token/core.py:69
#, python-format
msgid "User is disabled: %s"
msgstr ""

#: keystone/auth/controllers.py:267
msgid "Scoping to both domain and project is not allowed"
msgstr ""

#: keystone/auth/controllers.py:270
msgid "Scoping to both domain and trust is not allowed"
msgstr ""

#: keystone/auth/controllers.py:273
msgid "Scoping to both project and trust is not allowed"
msgstr ""

#: keystone/auth/controllers.py:360
#, python-format
msgid ""
"User %(user_id)s doesn't have access to default project %(project_id)s. "
"The token will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:367
#, python-format
msgid ""
"User %(user_id)s's default project %(project_id)s is disabled. The token "
"will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:376
#, python-format
msgid ""
"User %(user_id)s's default project %(project_id)s not found. The token "
"will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:407
msgid "User not found"
msgstr ""

#: keystone/auth/plugins/external.py:45
msgid "No authenticated user"
msgstr ""

#: keystone/auth/plugins/external.py:55
#, python-format
msgid "Unable to lookup user %s"
msgstr ""

#: keystone/auth/plugins/external.py:105
msgid ""
"keystone.auth.external.ExternalDefault is deprecated infavor of "
"keystone.auth.external.Default"
msgstr ""

#: keystone/auth/plugins/external.py:113
msgid ""
"keystone.auth.external.ExternalDomain is deprecated infavor of "
"keystone.auth.external.Domain"
msgstr ""

#: keystone/auth/plugins/oauth1.py:55
msgid "Access token is expired"
msgstr ""

#: keystone/auth/plugins/oauth1.py:75
#: keystone/contrib/oauth1/controllers.py:269
msgid "There should not be any non-oauth parameters"
msgstr ""

#: keystone/auth/plugins/password.py:120
msgid "Invalid username or password"
msgstr ""

#: keystone/catalog/core.py:42
#, python-format
msgid "Malformed endpoint %(url)s - unknown key %(keyerror)s"
msgstr ""

#: keystone/catalog/core.py:47
#, python-format
msgid ""
"Malformed endpoint %(url)s - unknown key %(keyerror)s(are you missing "
"brackets ?)"
msgstr ""

#: keystone/catalog/core.py:53
#, python-format
msgid ""
"Malformed endpoint %s - incomplete format (are you missing a type "
"notifier ?)"
msgstr ""

#: keystone/catalog/backends/templated.py:107
#, python-format
msgid "Unable to open template file %s"
msgstr ""

#: keystone/common/base64utils.py:207 keystone/common/base64utils.py:280
#: keystone/common/base64utils.py:334
msgid "pad must be single character"
msgstr ""

#: keystone/common/base64utils.py:213
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before 2nd to last char"
msgstr ""

#: keystone/common/base64utils.py:217
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before non-pad last char"
msgstr ""

#: keystone/common/base64utils.py:223
#, python-format
msgid "text is not a multiple of 4, but contains pad \"%s\""
msgstr ""

#: keystone/common/base64utils.py:242 keystone/common/base64utils.py:263
msgid "padded base64url text must be multiple of 4 characters"
msgstr ""

#: keystone/common/cms.py:42
#, python-format
msgid "Verify error: %s"
msgstr ""

#: keystone/common/cms.py:134
msgid ""
"Signing error: Unable to load certificate - ensure you've configured PKI "
"with 'keystone-manage pki_setup'"
msgstr ""

#: keystone/common/cms.py:138
#, python-format
msgid "Signing error: %s"
msgstr ""

#: keystone/common/controller.py:39
#, python-format
msgid "RBAC: Authorizing %(action)s(%(kwargs)s)"
msgstr ""

#: keystone/common/controller.py:46
msgid "RBAC: Invalid token"
msgstr ""

#: keystone/common/controller.py:60 keystone/common/controller.py:81
msgid "RBAC: Invalid user"
msgstr ""

#: keystone/common/controller.py:66
msgid "RBAC: Proceeding without project"
msgstr ""

#: keystone/common/controller.py:86
msgid "RBAC: Proceeding without tenant"
msgstr ""

#: keystone/common/controller.py:128 keystone/common/controller.py:215
#: keystone/common/controller.py:487
msgid "RBAC: Bypassing authorization"
msgstr ""

#: keystone/common/controller.py:173 keystone/common/controller.py:213
#: keystone/common/controller.py:503
msgid "RBAC: Authorization granted"
msgstr ""

#: keystone/common/controller.py:203
#, python-format
msgid "RBAC: Adding query filter params (%s)"
msgstr ""

#: keystone/common/controller.py:275
#, python-format
msgid "Project (%s)"
msgstr ""

#: keystone/common/controller.py:277
#, python-format
msgid "Domain (%s)"
msgstr ""

#: keystone/common/controller.py:279
msgid "Unknown Target"
msgstr ""

#: keystone/common/controller.py:280
#, python-format
msgid ""
"Group (%(group)s), referenced in assignment for %(target)s, not found - "
"ignoring."
msgstr ""

#: keystone/common/controller.py:458
msgid "Invalid token in _get_domain_id_for_request"
msgstr ""

#: keystone/common/pemutils.py:221
#, python-format
msgid "unknown pem_type \"%(pem_type)s\", valid types are: %(valid_pem_types)s"
msgstr ""

#: keystone/common/pemutils.py:240
#, python-format
msgid ""
"unknown pem header \"%(pem_header)s\", valid headers are: "
"%(valid_pem_headers)s"
msgstr ""

#: keystone/common/pemutils.py:298
#, python-format
msgid "failed to find end matching \"%s\""
msgstr ""

#: keystone/common/pemutils.py:302
#, python-format
msgid ""
"beginning & end PEM headers do not match (%(begin_pem_header)s!= "
"%(end_pem_header)s)"
msgstr ""

#: keystone/common/pemutils.py:377
#, python-format
msgid "unknown pem_type: \"%s\""
msgstr ""

#: keystone/common/pemutils.py:389
#, python-format
msgid ""
"failed to base64 decode %(pem_type)s PEM at position%(position)d: "
"%(err_msg)s"
msgstr ""

#: keystone/common/utils.py:76
#, python-format
msgid "Truncating user password to %s characters."
msgstr ""

#: keystone/common/utils.py:185 keystone/credential/controllers.py:42
msgid "Invalid blob in credential"
msgstr ""

#: keystone/common/utils.py:264
msgid ""
"Error setting up the debug environment. Verify that the option --debug-"
"url has the format <host>:<port> and that a debugger processes is "
"listening on that port."
msgstr ""

#: keystone/common/wsgi.py:72
msgid "No bind information present in token"
msgstr ""

#: keystone/common/wsgi.py:76
#, python-format
msgid "Named bind mode %s not in bind information"
msgstr ""

#: keystone/common/wsgi.py:83
msgid "Kerberos credentials required and not present"
msgstr ""

#: keystone/common/wsgi.py:87
msgid "Kerberos credentials do not match those in bind"
msgstr ""

#: keystone/common/wsgi.py:90
msgid "Kerberos bind authentication successful"
msgstr ""

#: keystone/common/wsgi.py:93
#, python-format
msgid "Ignoring unknown bind for permissive mode: {%(bind_type)s: %(identifier)s}"
msgstr ""

#: keystone/common/wsgi.py:97
#, python-format
msgid "Couldn't verify unknown bind: {%(bind_type)s: %(identifier)s}"
msgstr ""

#: keystone/common/wsgi.py:186
#, python-format
msgid "arg_dict: %s"
msgstr ""

#: keystone/common/wsgi.py:214
#, python-format
msgid "Authorization failed. %(exception)s from %(remote_addr)s"
msgstr ""

#: keystone/common/wsgi.py:462 keystone/tests/test_wsgi.py:282
msgid "The resource could not be found."
msgstr ""

#: keystone/common/cache/core.py:50
#, python-format
msgid "CACHE_GET: Key: \"%(key)r\" Value: \"%(value)r\""
msgstr ""

#: keystone/common/cache/core.py:56
#, python-format
msgid "CACHE_GET_MULTI: \"%(keys)r\" Values: \"%(values)r\""
msgstr ""

#: keystone/common/cache/core.py:61
#, python-format
msgid "CACHE_SET: Key: \"%(key)r\" Value: \"%(value)r\""
msgstr ""

#: keystone/common/cache/core.py:66
#, python-format
msgid "CACHE_SET_MULTI: \"%r\""
msgstr ""

#: keystone/common/cache/core.py:71
#, python-format
msgid "CACHE_DELETE: \"%r\""
msgstr ""

#: keystone/common/cache/core.py:74
#, python-format
msgid "CACHE_DELETE_MULTI: \"%r\""
msgstr ""

#: keystone/common/cache/core.py:92
#, python-format
msgid ""
"Unable to build cache config-key. Expected format \"<argname>:<value>\". "
"Skipping unknown format: %s"
msgstr ""

#: keystone/common/cache/core.py:100
#, python-format
msgid "Keystone Cache Config: %s"
msgstr ""

#: keystone/common/cache/core.py:115
msgid "region not type dogpile.cache.CacheRegion"
msgstr ""

#: keystone/common/cache/core.py:148
#, python-format
msgid "Adding cache-proxy '%s' to backend."
msgstr ""

#: keystone/common/environment/__init__.py:53
#, python-format
msgid "Environment configured as: %s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:50
#, python-format
msgid "Starting %(arg0)s on %(host)s:%(port)s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:112
msgid "Server error"
msgstr ""

#: keystone/common/kvs/core.py:61
#, python-format
msgid "Registering Dogpile Backend %(backend_path)s as %(backend_name)s"
msgstr ""

#: keystone/common/kvs/core.py:69
#, python-format
msgid "Lock Timeout occurred for key, %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:104
#, python-format
msgid "KVS region %s is already configured. Cannot reconfigure."
msgstr ""

#: keystone/common/kvs/core.py:120
#, python-format
msgid "Importing class %s as KVS proxy."
msgstr ""

#: keystone/common/kvs/core.py:128
#, python-format
msgid "%s is not a dogpile.proxy.ProxyBackend"
msgstr ""

#: keystone/common/kvs/core.py:132
#, python-format
msgid "Adding proxy '%(proxy)s' to KVS %(name)s."
msgstr ""

#: keystone/common/kvs/core.py:139
#, python-format
msgid "Key Value Store not configured: %s"
msgstr ""

#: keystone/common/kvs/core.py:162
#, python-format
msgid "Using %(func)s as KVS region %(name)s key_mangler"
msgstr ""

#: keystone/common/kvs/core.py:172
msgid "`key_mangler` option must be a function reference"
msgstr ""

#: keystone/common/kvs/core.py:174
#, python-format
msgid "Using default dogpile sha1_mangle_key as KVS region %s key_mangler"
msgstr ""

#: keystone/common/kvs/core.py:183
#, python-format
msgid "KVS region %s key_mangler disabled."
msgstr ""

#: keystone/common/kvs/core.py:211
#, python-format
msgid "KVS region configuration for %(name)s: %(config)r"
msgstr ""

#: keystone/common/kvs/core.py:324
#, python-format
msgid "Lock key must match target key: %(lock)s != %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:328
msgid "Must be called within an active lock context."
msgstr ""

#: keystone/common/kvs/core.py:352
#, python-format
msgid "KVS lock acquired for: %s"
msgstr ""

#: keystone/common/kvs/core.py:371
#, python-format
msgid "KVS lock released for: %s"
msgstr ""

#: keystone/common/kvs/core.py:373
#, python-format
msgid "KVS lock released (timeout reached) for: %s"
msgstr ""

#: keystone/common/kvs/backends/memcached.py:71
#, python-format
msgid "Maximum lock attempts on %s occured."
msgstr ""

#: keystone/common/kvs/backends/memcached.py:106
#, python-format
msgid "Backend `%s` is not a valid dogpile memcached backend."
msgstr ""

#: keystone/common/ldap/core.py:77
#, python-format
msgid "Invalid LDAP deref option: %s. Choose one of: "
msgstr ""

#: keystone/common/ldap/core.py:85
#, python-format
msgid "Invalid LDAP TLS certs option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:97
#, python-format
msgid "Invalid LDAP scope: %(scope)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:213
#, python-format
msgid ""
"Invalid additional attribute mapping: \"%s\". Format must be "
"<ldap_attribute>:<keystone_attribute>"
msgstr ""

#: keystone/common/ldap/core.py:219
#, python-format
msgid ""
"Invalid additional attribute mapping: \"%(item)s\". Value "
"\"%(attr_map)s\" must use one of %(keys)s."
msgstr ""

#: keystone/common/ldap/core.py:305 keystone/identity/backends/kvs.py:180
#: keystone/identity/backends/kvs.py:208
#, python-format
msgid "Duplicate name, %s."
msgstr ""

#: keystone/common/ldap/core.py:315 keystone/identity/backends/kvs.py:173
#, python-format
msgid "Duplicate ID, %s."
msgstr ""

#: keystone/common/ldap/core.py:321
#, python-format
msgid "LDAP %s create"
msgstr ""

#: keystone/common/ldap/core.py:407
#, python-format
msgid "LDAP %s update"
msgstr ""

#: keystone/common/ldap/core.py:423
#, python-format
msgid "Cannot change %(option_name)s %(attr)s"
msgstr ""

#: keystone/common/ldap/core.py:455
#, python-format
msgid "LDAP %s delete"
msgstr ""

#: keystone/common/ldap/core.py:484
#, python-format
msgid "LDAP init: url=%s"
msgstr ""

#: keystone/common/ldap/core.py:485
#, python-format
msgid ""
"LDAP init: use_tls=%(use_tls)s\n"
"tls_cacertfile=%(tls_cacertfile)s\n"
"tls_cacertdir=%(tls_cacertdir)s\n"
"tls_req_cert=%(tls_req_cert)s\n"
"tls_avail=%(tls_avail)s\n"
msgstr ""

#: keystone/common/ldap/core.py:504
msgid "Invalid TLS / LDAPS combination"
msgstr ""

#: keystone/common/ldap/core.py:508
#, python-format
msgid "Invalid LDAP TLS_AVAIL option: %s. TLS not available"
msgstr ""

#: keystone/common/ldap/core.py:518
#, python-format
msgid "tls_cacertfile %s not found or is not a file"
msgstr ""

#: keystone/common/ldap/core.py:530
#, python-format
msgid "tls_cacertdir %s not found or is not a directory"
msgstr ""

#: keystone/common/ldap/core.py:537
#, python-format
msgid "LDAP TLS: invalid TLS_REQUIRE_CERT Option=%s"
msgstr ""

#: keystone/common/ldap/core.py:551
#, python-format
msgid "LDAP bind: dn=%s"
msgstr ""

#: keystone/common/ldap/core.py:565
#, python-format
msgid "LDAP add: dn=%(dn)s, attrs=%(attrs)s"
msgstr ""

#: keystone/common/ldap/core.py:576
#, python-format
msgid ""
"LDAP search: dn=%(dn)s, scope=%(scope)s, query=%(query)s, "
"attrs=%(attrlist)s"
msgstr ""

#: keystone/common/ldap/core.py:629
msgid ""
"LDAP Server does not support paging. Disable paging in keystone.conf to "
"avoid this message."
msgstr ""

#: keystone/common/ldap/core.py:645
#, python-format
msgid "LDAP modify: dn=%(dn)s, modlist=%(modlist)s"
msgstr ""

#: keystone/common/ldap/core.py:651
#, python-format
msgid "LDAP delete: dn=%s"
msgstr ""

#: keystone/common/ldap/core.py:656
#, python-format
msgid "LDAP delete_ext: dn=%(dn)s, serverctrls=%(serverctrls)s"
msgstr ""

#: keystone/common/sql/migration.py:57
#: keystone/openstack/common/db/sqlalchemy/migration.py:220
msgid "version should be an integer"
msgstr ""

#: keystone/common/sql/migrate_repo/versions/033_migrate_ec2credentials_table_credentials.py:61
#, python-format
msgid ""
"Credential %(access)s already exists with different secret in %(table)s "
"table"
msgstr ""

#: keystone/common/sql/migrate_repo/versions/033_migrate_ec2credentials_table_credentials.py:71
#, python-format
msgid ""
"Credential %(access)s already exists with different project in %(table)s "
"table"
msgstr ""

#: keystone/contrib/ec2/controllers.py:254
msgid "Token belongs to another user"
msgstr ""

#: keystone/contrib/ec2/controllers.py:287
msgid "Credential belongs to another user"
msgstr ""

#: keystone/contrib/endpoint_filter/backends/sql.py:53
#, python-format
msgid "Endpoint %(endpoint_id)s not found in project %(project_id)s"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:70
msgid "Cannot change consumer secret"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:143
#: keystone/contrib/oauth1/backends/sql.py:279
msgid "User IDs do not match"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:150
msgid "Could not find role"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:198
msgid "Non-oauth parameter - project, do not match"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:248
#: keystone/contrib/oauth1/controllers.py:325
msgid "Request token is expired"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:273
msgid "provided consumer key does not match stored consumer key"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:277
msgid "provided verifier does not match stored verifier"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:281
msgid "provided request key does not match stored request key"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:285
msgid "Request Token does not have an authorizing user id"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:341
msgid "authorizing user does not have role required"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:356
msgid "User is not a member of the requested project"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:91
msgid "Consumer not found"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:195
msgid "Request token not found"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:259
msgid "Access token not found"
msgstr ""

#: keystone/identity/controllers.py:133
msgid "Enabled field must be a boolean"
msgstr ""

#: keystone/identity/controllers.py:159
msgid "Enabled field should be a boolean"
msgstr ""

#: keystone/identity/controllers.py:204
#, python-format
msgid "Unable to remove user %(user)s from %(tenant)s."
msgstr ""

#: keystone/identity/controllers.py:223
#, python-format
msgid "Unable to add user %(user)s to %(tenant)s."
msgstr ""

#: keystone/identity/core.py:105
#, python-format
msgid "Invalid domain name (%s) found in config file name"
msgstr ""

#: keystone/identity/core.py:129
#, python-format
msgid "Unable to locate domain config directory: %s"
msgstr ""

#: keystone/identity/core.py:142
#, python-format
msgid "Ignoring file (%s) while scanning domain config directory"
msgstr ""

#: keystone/identity/core.py:183
msgid ""
"Running an experimental and unsupported configuration "
"(domain_specific_drivers_enabled = True); this will result in known "
"issues."
msgstr ""

#: keystone/identity/backends/kvs.py:129 keystone/identity/backends/kvs.py:138
msgid "User not found in group"
msgstr ""

#: keystone/identity/backends/ldap.py:161
#, python-format
msgid ""
"Group member '%(user_dn)s' not found in '%(group_id)s'. The user should "
"be removed from the group. The user will be ignored."
msgstr ""

#: keystone/identity/backends/ldap.py:302
#, python-format
msgid "User %(user_id)s is already a member of group %(group_id)s"
msgstr ""

#: keystone/openstack/common/eventlet_backdoor.py:140
#, python-format
msgid "Eventlet backdoor listening on %(port)s for process %(pid)d"
msgstr ""

#: keystone/openstack/common/exception.py:103
msgid "Uncaught exception"
msgstr ""

#: keystone/openstack/common/excutils.py:62
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: keystone/openstack/common/excutils.py:91
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: keystone/openstack/common/fileutils.py:63
#, python-format
msgid "Reloading cached file %s"
msgstr ""

#: keystone/openstack/common/lockutils.py:103
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: keystone/openstack/common/lockutils.py:168
#, python-format
msgid "Got semaphore \"%(lock)s\""
msgstr ""

#: keystone/openstack/common/lockutils.py:177
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\""
msgstr ""

#: keystone/openstack/common/lockutils.py:187
#, python-format
msgid "Created lock path: %s"
msgstr ""

#: keystone/openstack/common/lockutils.py:205
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: keystone/openstack/common/lockutils.py:209
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: keystone/openstack/common/lockutils.py:247
#, python-format
msgid "Got semaphore / lock \"%(function)s\""
msgstr ""

#: keystone/openstack/common/lockutils.py:251
#, python-format
msgid "Semaphore / lock released \"%(function)s\""
msgstr ""

#: keystone/openstack/common/log.py:301
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: keystone/openstack/common/log.py:402
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: keystone/openstack/common/log.py:453
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: keystone/openstack/common/log.py:623
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: keystone/openstack/common/loopingcall.py:82
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: keystone/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr ""

#: keystone/openstack/common/loopingcall.py:129
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: keystone/openstack/common/loopingcall.py:136
msgid "in dynamic looping call"
msgstr ""

#: keystone/openstack/common/policy.py:73
msgid "JSON file containing policy"
msgstr ""

#: keystone/openstack/common/policy.py:76
msgid "Rule enforced when requested rule is not found"
msgstr ""

#: keystone/openstack/common/policy.py:90
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: keystone/openstack/common/policy.py:175
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: keystone/openstack/common/policy.py:205
msgid "Rules successfully reloaded"
msgstr ""

#: keystone/openstack/common/policy.py:251
#, python-format
msgid "Rule %s will be now enforced"
msgstr ""

#: keystone/openstack/common/policy.py:266
#, python-format
msgid "Rule [%s] doesn't exist"
msgstr ""

#: keystone/openstack/common/policy.py:474
#, python-format
msgid "Failed to understand rule %s"
msgstr ""

#: keystone/openstack/common/policy.py:484
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: keystone/openstack/common/policy.py:754
#, python-format
msgid "Failed to understand rule %r"
msgstr ""

#: keystone/openstack/common/processutils.py:130
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: keystone/openstack/common/processutils.py:145
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: keystone/openstack/common/processutils.py:169
#: keystone/openstack/common/processutils.py:241
#, python-format
msgid "Result was %s"
msgstr ""

#: keystone/openstack/common/processutils.py:181
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: keystone/openstack/common/processutils.py:220
#, python-format
msgid "Running cmd (SSH): %s"
msgstr ""

#: keystone/openstack/common/processutils.py:222
msgid "Environment not supported over SSH"
msgstr ""

#: keystone/openstack/common/processutils.py:226
msgid "process_input not supported over SSH"
msgstr ""

#: keystone/openstack/common/service.py:134
#: keystone/openstack/common/service.py:346
msgid "Full set of CONF:"
msgstr ""

#: keystone/openstack/common/service.py:143
#: keystone/openstack/common/service.py:231
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: keystone/openstack/common/service.py:155
msgid "Exception during rpc cleanup."
msgstr ""

#: keystone/openstack/common/service.py:200
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: keystone/openstack/common/service.py:237
msgid "Unhandled exception"
msgstr ""

#: keystone/openstack/common/service.py:270
msgid "Forking too fast, sleeping"
msgstr ""

#: keystone/openstack/common/service.py:289
#, python-format
msgid "Started child %d"
msgstr ""

#: keystone/openstack/common/service.py:299
#, python-format
msgid "Starting %d workers"
msgstr ""

#: keystone/openstack/common/service.py:316
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: keystone/openstack/common/service.py:320
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr ""

#: keystone/openstack/common/service.py:324
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: keystone/openstack/common/service.py:354
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: keystone/openstack/common/service.py:372
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: keystone/openstack/common/sslutils.py:50
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: keystone/openstack/common/sslutils.py:53
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: keystone/openstack/common/sslutils.py:56
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: keystone/openstack/common/sslutils.py:59
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: keystone/openstack/common/sslutils.py:98
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: keystone/openstack/common/strutils.py:86
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: keystone/openstack/common/strutils.py:182
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: keystone/openstack/common/strutils.py:189
#, python-format
msgid "Unknown byte multiplier: %s"
msgstr ""

#: keystone/openstack/common/versionutils.py:69
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: keystone/openstack/common/versionutils.py:73
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: keystone/openstack/common/crypto/utils.py:27
msgid "An unknown error occurred in crypto utils."
msgstr ""

#: keystone/openstack/common/crypto/utils.py:34
#, python-format
msgid "Block size of %(given)d is too big, max = %(maximum)d"
msgstr ""

#: keystone/openstack/common/crypto/utils.py:43
#, python-format
msgid "Length of %(given)d is too long, max = %(maximum)d"
msgstr ""

#: keystone/openstack/common/db/exception.py:42
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/migration.py:252
msgid "Upgrade DB using Essex release first."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/session.py:553
msgid "DB exception wrapped."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/session.py:621
#, python-format
msgid "Database server has gone away: %s"
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/session.py:704
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/test_migrations.py:103
#, python-format
msgid "Got lock \"%s\""
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/test_migrations.py:106
#, python-format
msgid "Lock released \"%s\""
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:58
msgid "Sort key supplied was not valid."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:97
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:119
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:194
#, python-format
msgid ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:200
#, python-format
msgid ""
"col_name_col_instance param has wrong type of column instance for column "
"%s It should be instance of sqlalchemy.Column."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:280
#, python-format
msgid "Deleting duplicated row with id: %(id)s from table: %(table)s"
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:301
msgid "Unsupported id columns type"
msgstr ""

#: keystone/openstack/common/notifier/api.py:129
#, python-format
msgid "%s not in valid priorities"
msgstr ""

#: keystone/openstack/common/notifier/api.py:145
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""

#: keystone/openstack/common/notifier/api.py:164
#, python-format
msgid "Failed to load notifier %s. These notifications will not be sent."
msgstr ""

#: keystone/openstack/common/notifier/rpc_notifier.py:45
#: keystone/openstack/common/notifier/rpc_notifier2.py:51
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr ""

#: keystone/openstack/common/rpc/__init__.py:103
#, python-format
msgid ""
"A RPC is being made while holding a lock. The locks currently held are "
"%(locks)s. This is probably a bug. Please report it. Include the "
"following: [%(stack)s]."
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:73
msgid "Pool creating new connection"
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:200
#, python-format
msgid "No calling threads waiting for msg_id : %(msg_id)s, message : %(data)s"
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:203
#, python-format
msgid "_call_waiters: %s"
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:210
#, python-format
msgid ""
"Number of call waiters is greater than warning threshold: %d. There could"
" be a MulticallProxyWaiter leak."
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:288
#, python-format
msgid "unpacked context: %s"
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:339
#, python-format
msgid "UNIQUE_ID is %s."
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:432
#, python-format
msgid "received %s"
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:440
#, python-format
msgid "no method for message: %s"
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:441
#, python-format
msgid "No method for message: %s"
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:469
#: keystone/openstack/common/rpc/impl_zmq.py:280
#, python-format
msgid "Expected exception during message handling (%s)"
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:477
#: keystone/openstack/common/rpc/impl_zmq.py:286
msgid "Exception during message handling"
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:551
#, python-format
msgid "Making synchronous call on %s ..."
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:554
#, python-format
msgid "MSG_ID is %s"
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:580
#, python-format
msgid "Making asynchronous cast on %s..."
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:589
msgid "Making asynchronous fanout cast..."
msgstr ""

#: keystone/openstack/common/rpc/amqp.py:617
#, python-format
msgid "Sending %(event_type)s on %(topic)s"
msgstr ""

#: keystone/openstack/common/rpc/common.py:76
msgid "An unknown RPC related exception occurred."
msgstr ""

#: keystone/openstack/common/rpc/common.py:88
msgid "Exception in string format operation"
msgstr ""

#: keystone/openstack/common/rpc/common.py:106
#, python-format
msgid ""
"Remote error: %(exc_type)s %(value)s\n"
"%(traceback)s."
msgstr ""

#: keystone/openstack/common/rpc/common.py:123
#, python-format
msgid ""
"Timeout while waiting on RPC response - topic: \"%(topic)s\", RPC method:"
" \"%(method)s\" info: \"%(info)s\""
msgstr ""

#: keystone/openstack/common/rpc/common.py:140
#: keystone/openstack/common/rpc/common.py:141
#: keystone/openstack/common/rpc/common.py:142
msgid "<unknown>"
msgstr ""

#: keystone/openstack/common/rpc/common.py:146
#, python-format
msgid "Found duplicate message(%(msg_id)s). Skipping it."
msgstr ""

#: keystone/openstack/common/rpc/common.py:150
msgid "Invalid reuse of an RPC connection."
msgstr ""

#: keystone/openstack/common/rpc/common.py:154
#, python-format
msgid "Specified RPC version, %(version)s, not supported by this endpoint."
msgstr ""

#: keystone/openstack/common/rpc/common.py:159
#, python-format
msgid ""
"Specified RPC envelope version, %(version)s, not supported by this "
"endpoint."
msgstr ""

#: keystone/openstack/common/rpc/common.py:164
#, python-format
msgid "Specified RPC version cap, %(version_cap)s, is too low"
msgstr ""

#: keystone/openstack/common/rpc/common.py:288
#, python-format
msgid "Returning exception %s to caller"
msgstr ""

#: keystone/openstack/common/rpc/impl_kombu.py:156
msgid "Failed to process message ... skipping it."
msgstr ""

#: keystone/openstack/common/rpc/impl_kombu.py:160
msgid "Failed to process message ... will requeue."
msgstr ""

#: keystone/openstack/common/rpc/impl_kombu.py:495
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: keystone/openstack/common/rpc/impl_kombu.py:517
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: keystone/openstack/common/rpc/impl_kombu.py:554
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""

#: keystone/openstack/common/rpc/impl_kombu.py:568
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""

#: keystone/openstack/common/rpc/impl_kombu.py:622
#: keystone/openstack/common/rpc/impl_qpid.py:573
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr ""

#: keystone/openstack/common/rpc/impl_kombu.py:640
#: keystone/openstack/common/rpc/impl_qpid.py:588
#, python-format
msgid "Timed out waiting for RPC response: %s"
msgstr ""

#: keystone/openstack/common/rpc/impl_kombu.py:644
#: keystone/openstack/common/rpc/impl_qpid.py:592
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr ""

#: keystone/openstack/common/rpc/impl_kombu.py:683
#: keystone/openstack/common/rpc/impl_qpid.py:627
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr ""

#: keystone/openstack/common/rpc/impl_qpid.py:87
#, python-format
msgid "Invalid value for qpid_topology_version: %d"
msgstr ""

#: keystone/openstack/common/rpc/impl_qpid.py:191
msgid "Failed to process message... skipping it."
msgstr ""

#: keystone/openstack/common/rpc/impl_qpid.py:515
#, python-format
msgid "Unable to connect to AMQP server: %(e)s. Sleeping %(delay)s seconds"
msgstr ""

#: keystone/openstack/common/rpc/impl_qpid.py:521
#, python-format
msgid "Connected to AMQP server on %s"
msgstr ""

#: keystone/openstack/common/rpc/impl_qpid.py:534
msgid "Re-established AMQP queues"
msgstr ""

#: keystone/openstack/common/rpc/impl_qpid.py:600
msgid "Error processing message.  Skipping it."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:96
msgid "JSON serialization failed."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:101
#, python-format
msgid "Deserializing: %s"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:136
#, python-format
msgid "Connecting to %(addr)s with %(type)s"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:137
#, python-format
msgid "-> Subscribed to %(subscribe)s"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:138
#, python-format
msgid "-> bind: %(bind)s"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:146
msgid "Could not open socket."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:158
#, python-format
msgid "Subscribing to %s"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:195
msgid "ZeroMQ socket could not be closed."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:200
msgid "You cannot recv on this socket."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:205
msgid "You cannot send on this socket."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:267
#, python-format
msgid "Running func with context: %s"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:305
msgid "Sending reply"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:339
msgid "RPC message did not include method."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:371
msgid "Registering reactor"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:383
msgid "In reactor registered"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:388
msgid "Consuming socket"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:438
#, python-format
msgid "Creating proxy for topic: %s"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:444
msgid "Topic contained dangerous characters."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:476
msgid "Topic socket file creation failed."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:482
#, python-format
msgid "Local per-topic backlog buffer full for topic %(topic)s. Dropping message."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:498
#, python-format
msgid "Required IPC directory does not exist at %s"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:507
#, python-format
msgid "Permission denied to IPC directory at %s"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:510
msgid "Could not create ZeroMQ receiver daemon. Socket may already be in use."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:544
#, python-format
msgid "CONSUMER RECEIVED DATA: %s"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:563
msgid "ZMQ Envelope version unsupported or unknown."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:591
msgid "Skipping topic registration. Already registered."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:598
#, python-format
msgid "Consumer is a zmq.%s"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:650
msgid "Creating payload"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:663
msgid "Creating queue socket for reply waiter"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:676
msgid "Sending cast"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:679
msgid "Cast sent; Waiting reply"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:682
#, python-format
msgid "Received message: %s"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:683
msgid "Unpacking response"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:692
msgid "Unsupported or unknown ZMQ envelope returned."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:699
msgid "RPC Message Invalid."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:722
#, python-format
msgid "%(msg)s"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:725
#, python-format
msgid "Sending message(s) to: %s"
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:729
msgid "No matchmaker results. Not casting."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:732
msgid "No match from matchmaker."
msgstr ""

#: keystone/openstack/common/rpc/impl_zmq.py:814
#, python-format
msgid "rpc_zmq_matchmaker = %(orig)s is deprecated; use %(new)s instead"
msgstr ""

#: keystone/openstack/common/rpc/matchmaker.py:45
msgid "Match not found by MatchMaker."
msgstr ""

#: keystone/openstack/common/rpc/matchmaker.py:79
msgid "Matchmaker does not implement registration or heartbeat."
msgstr ""

#: keystone/openstack/common/rpc/matchmaker.py:215
#, python-format
msgid "Matchmaker unregistered: %(key)s, %(host)s"
msgstr ""

#: keystone/openstack/common/rpc/matchmaker.py:227
msgid "Register before starting heartbeat."
msgstr ""

#: keystone/openstack/common/rpc/matchmaker_ring.py:75
#: keystone/openstack/common/rpc/matchmaker_ring.py:93
#, python-format
msgid "No key defining hosts for topic '%s', see ringfile"
msgstr ""

#: keystone/openstack/common/rpc/service.py:47
#, python-format
msgid "Creating Consumer connection for Service %s"
msgstr ""

#: keystone/policy/backends/rules.py:100
#, python-format
msgid "enforce %(action)s: %(credentials)s"
msgstr ""

#: keystone/tests/core.py:136
#, python-format
msgid "Failed to checkout %s"
msgstr ""

#: keystone/tests/fakeldap.py:162
#, python-format
msgid "FakeLdap initialize url=%s"
msgstr ""

#: keystone/tests/fakeldap.py:174
#, python-format
msgid "FakeLdap bind dn=%s"
msgstr ""

#: keystone/tests/fakeldap.py:181
#, python-format
msgid "FakeLdap bind fail: dn=%s not found"
msgstr ""

#: keystone/tests/fakeldap.py:188
#, python-format
msgid "FakeLdap bind fail: password for dn=%s not found"
msgstr ""

#: keystone/tests/fakeldap.py:193
#, python-format
msgid "FakeLdap bind fail: password for dn=%s does not match"
msgstr ""

#: keystone/tests/fakeldap.py:213
#, python-format
msgid "FakeLdap add item: dn=%(dn)s, attrs=%(attrs)s"
msgstr ""

#: keystone/tests/fakeldap.py:216
#, python-format
msgid "FakeLdap add item failed: dn=%s is already in store."
msgstr ""

#: keystone/tests/fakeldap.py:230 keystone/tests/fakeldap.py:244
#, python-format
msgid "FakeLdap delete item: dn=%s"
msgstr ""

#: keystone/tests/fakeldap.py:234 keystone/tests/fakeldap.py:248
#, python-format
msgid "FakeLdap delete item failed: dn=%s not found."
msgstr ""

#: keystone/tests/fakeldap.py:263
#, python-format
msgid "FakeLdap modify item: dn=%(dn)s attrs=%(attrs)s"
msgstr ""

#: keystone/tests/fakeldap.py:268
#, python-format
msgid "FakeLdap modify item failed: dn=%s not found."
msgstr ""

#: keystone/tests/fakeldap.py:284
#, python-format
msgid "FakeLdap modify item failed: item has no attribute \"%s\" to delete"
msgstr ""

#: keystone/tests/fakeldap.py:293
#, python-format
msgid ""
"FakeLdap modify item failed: item has no attribute \"%(k)s\" with value "
"\"%(v)s\" to delete"
msgstr ""

#: keystone/tests/fakeldap.py:299
#, python-format
msgid "FakeLdap modify item failed: unknown command %s"
msgstr ""

#: keystone/tests/fakeldap.py:301
#, python-format
msgid "modify_s action %s not implemented"
msgstr ""

#: keystone/tests/fakeldap.py:320
#, python-format
msgid "FakeLdap search at dn=%(dn)s scope=%(scope)s query=%(query)s"
msgstr ""

#: keystone/tests/fakeldap.py:326
msgid "FakeLdap search fail: dn not found for SCOPE_BASE"
msgstr ""

#: keystone/tests/fakeldap.py:340
#, python-format
msgid "Search scope %s not implemented."
msgstr ""

#: keystone/token/controllers.py:380
#, python-format
msgid "User %(u_id)s is unauthorized for tenant %(t_id)s"
msgstr ""

#: keystone/token/controllers.py:397 keystone/token/controllers.py:400
msgid "Token does not belong to specified tenant."
msgstr ""

#: keystone/token/core.py:84
#, python-format
msgid "Tenant is disabled: %s"
msgstr ""

#: keystone/token/provider.py:85
msgid ""
"keystone.conf [signing] token_format (deprecated) conflicts with "
"keystone.conf [token] provider"
msgstr ""

#: keystone/token/provider.py:93
msgid ""
"keystone.conf [signing] token_format is deprecated in favor of "
"keystone.conf [token] provider"
msgstr ""

#: keystone/token/provider.py:103
msgid ""
"Unrecognized keystone.conf [signing] token_format: expected either 'UUID'"
" or 'PKI'"
msgstr ""

#: keystone/token/provider.py:193
#, python-format
msgid "Unexpected error or malformed token determining token expiry: %s"
msgstr ""

#: keystone/token/provider.py:200 keystone/token/providers/common.py:548
#: keystone/token/providers/common.py:558
msgid "Failed to validate token"
msgstr ""

#: keystone/token/backends/kvs.py:37
msgid ""
"kvs token backend is DEPRECATED. Use keystone.token.backends.sql or "
"keystone.token.backend.memcache instead."
msgstr ""

#: keystone/token/backends/memcache.py:142
#, python-format
msgid ""
"Successful set of token-index-list for user-key \"%(user_key)s\", "
"#%(count)d records"
msgstr ""

#: keystone/token/backends/memcache.py:152
#, python-format
msgid ""
"Failed to set token-index-list for user-key \"%(user_key)s\". Attempt "
"%(cas_retry)d of %(cas_retry_max)d"
msgstr ""

#: keystone/token/backends/memcache.py:161
msgid "Unable to add token user list"
msgstr ""

#: keystone/token/backends/memcache.py:170
msgid "Unable to add token to revocation list."
msgstr ""

#: keystone/token/providers/common.py:184
msgid "Trustor is disabled."
msgstr ""

#: keystone/token/providers/common.py:248
msgid "Trustee has no delegated roles."
msgstr ""

#: keystone/token/providers/common.py:257
#, python-format
msgid "User %(user_id)s has no access to project %(project_id)s"
msgstr ""

#: keystone/token/providers/common.py:262
#, python-format
msgid "User %(user_id)s has no access to domain %(domain_id)s"
msgstr ""

#: keystone/token/providers/common.py:312
msgid "User is not a trustee."
msgstr ""

#: keystone/token/providers/common.py:402
msgid "Oauth is disabled."
msgstr ""

#: keystone/token/providers/common.py:476
msgid "Non-default domain is not supported"
msgstr ""

#: keystone/token/providers/common.py:484
msgid "Domain scoped token is not supported"
msgstr ""

#: keystone/token/providers/pki.py:42
msgid "Unable to sign token"
msgstr ""

#: keystone/token/providers/pki.py:43
msgid "Unable to sign token."
msgstr ""

#~ msgid "CACHE_GET: Key: \"%(key)s)\" \"%(value)s\""
#~ msgstr ""

#~ msgid "CACHE_GET_MULTI: \"%(key)s\" \"%(value)s\""
#~ msgstr ""

#~ msgid "CACHE_SET: Key: %(key)s Value: %(value)s"
#~ msgstr ""

#~ msgid "CACHE_SET_MULTI: %s"
#~ msgstr ""

#~ msgid "CACHE_DELETE: %s"
#~ msgstr ""

#~ msgid "CACHE_DELETE_MULTI: %s"
#~ msgstr ""

#~ msgid "Invalid LDAP TLS certs option: %(option). Choose one of: %(options)s"
#~ msgstr ""

#~ msgid "Non-oauth parameter - roles, do not match"
#~ msgstr ""

#~ msgid "could not find matching roles for provided role ids"
#~ msgstr ""

#~ msgid "Failed to understand rule %(rule)s"
#~ msgstr ""

#~ msgid "Failed to understand rule %(rule)r"
#~ msgstr ""

#~ msgid ""
#~ "The Keystone paste configuration file "
#~ "%(config_file)s could not be found."
#~ msgstr ""

#~ msgid ""
#~ "Malformed endpoint %s - incomplete "
#~ "format                   (are you missing a"
#~ " type notifier ?)"
#~ msgstr ""

#~ msgid "CACHE_GET: Key: \"%(key)s\" Value: \"%(value)s\""
#~ msgstr ""

#~ msgid "CACHE_GET_MULTI: \"%(keys)s\" Values: \"%(values)s\""
#~ msgstr ""

#~ msgid "CACHE_SET: Key: \"%(key)s\" Value: \"%(value)s\""
#~ msgstr ""

#~ msgid "CACHE_SET_MULTI: \"%s\""
#~ msgstr ""

#~ msgid "CACHE_DELETE: \"%s\""
#~ msgstr ""

#~ msgid "CACHE_DELETE_MULTI: \"%s\""
#~ msgstr ""

#~ msgid "Global engine callback raised."
#~ msgstr ""

#~ msgid "MySQL server has gone away: %s"
#~ msgstr ""

#~ msgid "DB2 server has gone away: %s"
#~ msgstr ""

#~ msgid "Got mysql server has gone away: %s"
#~ msgstr ""

#~ msgid ""
#~ "Number of call waiters is greater "
#~ "than warning threshhold: %d. There could"
#~ " be a MulticallProxyWaiter leak."
#~ msgstr ""

